import { Municipality, SocialAction } from './types';

export const MOCK_MUNICIPALITIES: Municipality[] = [
  {
    id: '1',
    name: 'Belém',
    state: 'PA',
    region: 'Norte',
    povertyRate: 45.2,
    extremePovertyRate: 12.5,
    foodInsecurityRate: 38.4,
    cadUnicoCoverage: 82.0,
    schoolDropoutRate: 8.2,
    vulnerabilityScore: 72.5,
    riskLevel: 'Alto',
    coordinates: [-1.4558, -48.4902],
  },
  {
    id: '2',
    name: 'Maceió',
    state: 'AL',
    region: 'Nordeste',
    povertyRate: 52.1,
    extremePovertyRate: 18.2,
    foodInsecurityRate: 42.1,
    cadUnicoCoverage: 75.5,
    schoolDropoutRate: 10.5,
    vulnerabilityScore: 85.4,
    riskLevel: 'Crítico',
    coordinates: [-9.6658, -35.7353],
  },
  {
    id: '3',
    name: 'São Paulo',
    state: 'SP',
    region: 'Sudeste',
    povertyRate: 15.4,
    extremePovertyRate: 3.2,
    foodInsecurityRate: 12.5,
    cadUnicoCoverage: 95.0,
    schoolDropoutRate: 2.1,
    vulnerabilityScore: 22.1,
    riskLevel: 'Baixo',
    coordinates: [-23.5505, -46.6333],
  },
  {
    id: '4',
    name: 'Goiânia',
    state: 'GO',
    region: 'Centro-Oeste',
    povertyRate: 22.5,
    extremePovertyRate: 5.1,
    foodInsecurityRate: 18.2,
    cadUnicoCoverage: 88.4,
    schoolDropoutRate: 4.5,
    vulnerabilityScore: 35.2,
    riskLevel: 'Médio',
    coordinates: [-16.6869, -49.2648],
  },
  {
    id: '5',
    name: 'Porto Alegre',
    state: 'RS',
    region: 'Sul',
    povertyRate: 18.2,
    extremePovertyRate: 4.0,
    foodInsecurityRate: 14.1,
    cadUnicoCoverage: 92.1,
    schoolDropoutRate: 3.2,
    vulnerabilityScore: 28.5,
    riskLevel: 'Baixo',
    coordinates: [-30.0346, -51.2177],
  },
  {
    id: '6',
    name: 'Manaus',
    state: 'AM',
    region: 'Norte',
    povertyRate: 48.5,
    extremePovertyRate: 15.1,
    foodInsecurityRate: 40.2,
    cadUnicoCoverage: 78.2,
    schoolDropoutRate: 9.1,
    vulnerabilityScore: 78.9,
    riskLevel: 'Crítico',
    coordinates: [-3.1190, -60.0217],
  },
  {
    id: '7',
    name: 'Fortaleza',
    state: 'CE',
    region: 'Nordeste',
    povertyRate: 42.1,
    extremePovertyRate: 11.2,
    foodInsecurityRate: 35.5,
    cadUnicoCoverage: 85.1,
    schoolDropoutRate: 7.2,
    vulnerabilityScore: 65.4,
    riskLevel: 'Alto',
    coordinates: [-3.7172, -38.5433],
  },
];

export const MOCK_ACTIONS: SocialAction[] = [
  {
    id: 'a1',
    title: 'Ampliação do CRAS Central',
    description: 'Reforma e ampliação da capacidade de atendimento do CRAS no centro da cidade.',
    municipalityId: '2',
    status: 'Em Execução',
    targetDate: '2026-08-15',
    progress: 45,
  },
  {
    id: 'a2',
    title: 'Mutirão CadÚnico',
    description: 'Ação itinerante para atualização cadastral em comunidades rurais.',
    municipalityId: '6',
    status: 'Planejado',
    targetDate: '2026-05-20',
    progress: 0,
  },
  {
    id: 'a3',
    title: 'Programa de Segurança Alimentar',
    description: 'Distribuição de cestas básicas e implantação de cozinha comunitária.',
    municipalityId: '1',
    status: 'Concluído',
    targetDate: '2026-03-01',
    progress: 100,
  },
  {
    id: 'a4',
    title: 'Capacitação de Equipes Técnicas',
    description: 'Treinamento para assistentes sociais sobre novos protocolos do SUAS.',
    municipalityId: '4',
    status: 'Atrasado',
    targetDate: '2026-04-01',
    progress: 20,
  },
];
